apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
        - name: emptydisk
          disk:
            bus: virtio
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - name: default
          masquerade: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "1Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        password: fedora
        chpasswd: { expire: False }
